name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
  
jobs:
  build:
    name: Build and test

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        with:
          submodules: recursive
      - name: Install GCC
        if: runner.os == 'Linux'
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
          
      - name: Install Ninja (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y ninja-build
      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja
      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install ninja --global
          # Scoop modifies the PATH so we make the modified PATH global.
          echo "PATH=$env:PATH" >> $GITHUB_ENV

      - name: build debug
        run: make debug
        shell: bash
      - name: build release
        run: make release
        shell: bash
